//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechfixClientDesktopApp.techFixServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int productIdField;
        
        private int supplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int stockField;
        
        private double unitPriceField;
        
        private double discountField;
        
        private System.DateTime createdAtField;
        
        private System.DateTime updatedAtField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int supplierId {
            get {
                return this.supplierIdField;
            }
            set {
                if ((this.supplierIdField.Equals(value) != true)) {
                    this.supplierIdField = value;
                    this.RaisePropertyChanged("supplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                if ((this.unitPriceField.Equals(value) != true)) {
                    this.unitPriceField = value;
                    this.RaisePropertyChanged("unitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime createdAt {
            get {
                return this.createdAtField;
            }
            set {
                if ((this.createdAtField.Equals(value) != true)) {
                    this.createdAtField = value;
                    this.RaisePropertyChanged("createdAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime updatedAt {
            get {
                return this.updatedAtField;
            }
            set {
                if ((this.updatedAtField.Equals(value) != true)) {
                    this.updatedAtField = value;
                    this.RaisePropertyChanged("updatedAt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int supplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string supplierNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int supplierId {
            get {
                return this.supplierIdField;
            }
            set {
                if ((this.supplierIdField.Equals(value) != true)) {
                    this.supplierIdField = value;
                    this.RaisePropertyChanged("supplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string supplierName {
            get {
                return this.supplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.supplierNameField, value) != true)) {
                    this.supplierNameField = value;
                    this.RaisePropertyChanged("supplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Quotation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Quotation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int quotationIdField;
        
        private int supplierIdField;
        
        private System.DateTime requestDateField;
        
        private System.DateTime approveDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quotationId {
            get {
                return this.quotationIdField;
            }
            set {
                if ((this.quotationIdField.Equals(value) != true)) {
                    this.quotationIdField = value;
                    this.RaisePropertyChanged("quotationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int supplierId {
            get {
                return this.supplierIdField;
            }
            set {
                if ((this.supplierIdField.Equals(value) != true)) {
                    this.supplierIdField = value;
                    this.RaisePropertyChanged("supplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime approveDate {
            get {
                return this.approveDateField;
            }
            set {
                if ((this.approveDateField.Equals(value) != true)) {
                    this.approveDateField = value;
                    this.RaisePropertyChanged("approveDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotationDetail", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class QuotationDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int quotationDetailIdField;
        
        private int quotationIdField;
        
        private int productIdField;
        
        private decimal unitPriceField;
        
        private decimal supplierDiscountField;
        
        private int quantityField;
        
        private System.Nullable<decimal> requestedDiscountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quotationDetailId {
            get {
                return this.quotationDetailIdField;
            }
            set {
                if ((this.quotationDetailIdField.Equals(value) != true)) {
                    this.quotationDetailIdField = value;
                    this.RaisePropertyChanged("quotationDetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int quotationId {
            get {
                return this.quotationIdField;
            }
            set {
                if ((this.quotationIdField.Equals(value) != true)) {
                    this.quotationIdField = value;
                    this.RaisePropertyChanged("quotationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int productId {
            get {
                return this.productIdField;
            }
            set {
                if ((this.productIdField.Equals(value) != true)) {
                    this.productIdField = value;
                    this.RaisePropertyChanged("productId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                if ((this.unitPriceField.Equals(value) != true)) {
                    this.unitPriceField = value;
                    this.RaisePropertyChanged("unitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal supplierDiscount {
            get {
                return this.supplierDiscountField;
            }
            set {
                if ((this.supplierDiscountField.Equals(value) != true)) {
                    this.supplierDiscountField = value;
                    this.RaisePropertyChanged("supplierDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> requestedDiscount {
            get {
                return this.requestedDiscountField;
            }
            set {
                if ((this.requestedDiscountField.Equals(value) != true)) {
                    this.requestedDiscountField = value;
                    this.RaisePropertyChanged("requestedDiscount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="techFixServices.TechFixWebServicesSoap")]
    public interface TechFixWebServicesSoap {
        
        // CODEGEN: Generating message contract since element name newProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewProduct", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.AddNewProductResponse AddNewProduct(TechfixClientDesktopApp.techFixServices.AddNewProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewProductResponse> AddNewProductAsync(TechfixClientDesktopApp.techFixServices.AddNewProductRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.GetAllProductsResponse GetAllProducts(TechfixClientDesktopApp.techFixServices.GetAllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetAllProductsResponse> GetAllProductsAsync(TechfixClientDesktopApp.techFixServices.GetAllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name newProduct from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.UpdateProductResponse UpdateProduct(TechfixClientDesktopApp.techFixServices.UpdateProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.UpdateProductResponse> UpdateProductAsync(TechfixClientDesktopApp.techFixServices.UpdateProductRequest request);
        
        // CODEGEN: Generating message contract since element name newSupplier from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewSupplier", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse AddNewSupplier(TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewSupplier", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse> AddNewSupplierAsync(TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest request);
        
        // CODEGEN: Generating message contract since element name GetSuppliersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSuppliers", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.GetSuppliersResponse GetSuppliers(TechfixClientDesktopApp.techFixServices.GetSuppliersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSuppliers", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetSuppliersResponse> GetSuppliersAsync(TechfixClientDesktopApp.techFixServices.GetSuppliersRequest request);
        
        // CODEGEN: Generating message contract since element name newQuotation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateQuotationRequest", ReplyAction="*")]
        TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse CreateQuotationRequest(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateQuotationRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse> CreateQuotationRequestAsync(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.AddNewProductRequestBody Body;
        
        public AddNewProductRequest() {
        }
        
        public AddNewProductRequest(TechfixClientDesktopApp.techFixServices.AddNewProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Product newProduct;
        
        public AddNewProductRequestBody() {
        }
        
        public AddNewProductRequestBody(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            this.newProduct = newProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.AddNewProductResponseBody Body;
        
        public AddNewProductResponse() {
        }
        
        public AddNewProductResponse(TechfixClientDesktopApp.techFixServices.AddNewProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddNewProductResult;
        
        public AddNewProductResponseBody() {
        }
        
        public AddNewProductResponseBody(int AddNewProductResult) {
            this.AddNewProductResult = AddNewProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest() {
        }
        
        public GetAllProductsRequest(TechfixClientDesktopApp.techFixServices.GetAllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody {
        
        public GetAllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse() {
        }
        
        public GetAllProductsResponse(TechfixClientDesktopApp.techFixServices.GetAllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Product[] GetAllProductsResult;
        
        public GetAllProductsResponseBody() {
        }
        
        public GetAllProductsResponseBody(TechfixClientDesktopApp.techFixServices.Product[] GetAllProductsResult) {
            this.GetAllProductsResult = GetAllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProduct", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.UpdateProductRequestBody Body;
        
        public UpdateProductRequest() {
        }
        
        public UpdateProductRequest(TechfixClientDesktopApp.techFixServices.UpdateProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Product newProduct;
        
        public UpdateProductRequestBody() {
        }
        
        public UpdateProductRequestBody(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            this.newProduct = newProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.UpdateProductResponseBody Body;
        
        public UpdateProductResponse() {
        }
        
        public UpdateProductResponse(TechfixClientDesktopApp.techFixServices.UpdateProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateProductResult;
        
        public UpdateProductResponseBody() {
        }
        
        public UpdateProductResponseBody(int UpdateProductResult) {
            this.UpdateProductResult = UpdateProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewSupplier", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.AddNewSupplierRequestBody Body;
        
        public AddNewSupplierRequest() {
        }
        
        public AddNewSupplierRequest(TechfixClientDesktopApp.techFixServices.AddNewSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewSupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Supplier newSupplier;
        
        public AddNewSupplierRequestBody() {
        }
        
        public AddNewSupplierRequestBody(TechfixClientDesktopApp.techFixServices.Supplier newSupplier) {
            this.newSupplier = newSupplier;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddNewSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddNewSupplierResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.AddNewSupplierResponseBody Body;
        
        public AddNewSupplierResponse() {
        }
        
        public AddNewSupplierResponse(TechfixClientDesktopApp.techFixServices.AddNewSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddNewSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddNewSupplierResult;
        
        public AddNewSupplierResponseBody() {
        }
        
        public AddNewSupplierResponseBody(int AddNewSupplierResult) {
            this.AddNewSupplierResult = AddNewSupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSuppliersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSuppliers", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.GetSuppliersRequestBody Body;
        
        public GetSuppliersRequest() {
        }
        
        public GetSuppliersRequest(TechfixClientDesktopApp.techFixServices.GetSuppliersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetSuppliersRequestBody {
        
        public GetSuppliersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSuppliersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSuppliersResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.GetSuppliersResponseBody Body;
        
        public GetSuppliersResponse() {
        }
        
        public GetSuppliersResponse(TechfixClientDesktopApp.techFixServices.GetSuppliersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSuppliersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Supplier[] GetSuppliersResult;
        
        public GetSuppliersResponseBody() {
        }
        
        public GetSuppliersResponseBody(TechfixClientDesktopApp.techFixServices.Supplier[] GetSuppliersResult) {
            this.GetSuppliersResult = GetSuppliersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQuotationRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQuotationRequest", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequestBody Body;
        
        public CreateQuotationRequestRequest() {
        }
        
        public CreateQuotationRequestRequest(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateQuotationRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechfixClientDesktopApp.techFixServices.Quotation newQuotation;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TechfixClientDesktopApp.techFixServices.QuotationDetail[] itemList;
        
        public CreateQuotationRequestRequestBody() {
        }
        
        public CreateQuotationRequestRequestBody(TechfixClientDesktopApp.techFixServices.Quotation newQuotation, TechfixClientDesktopApp.techFixServices.QuotationDetail[] itemList) {
            this.newQuotation = newQuotation;
            this.itemList = itemList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateQuotationRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateQuotationRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponseBody Body;
        
        public CreateQuotationRequestResponse() {
        }
        
        public CreateQuotationRequestResponse(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateQuotationRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateQuotationRequestResult;
        
        public CreateQuotationRequestResponseBody() {
        }
        
        public CreateQuotationRequestResponseBody(int CreateQuotationRequestResult) {
            this.CreateQuotationRequestResult = CreateQuotationRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TechFixWebServicesSoapChannel : TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TechFixWebServicesSoapClient : System.ServiceModel.ClientBase<TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap>, TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap {
        
        public TechFixWebServicesSoapClient() {
        }
        
        public TechFixWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TechFixWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechFixWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TechFixWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.AddNewProductResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.AddNewProduct(TechfixClientDesktopApp.techFixServices.AddNewProductRequest request) {
            return base.Channel.AddNewProduct(request);
        }
        
        public int AddNewProduct(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            TechfixClientDesktopApp.techFixServices.AddNewProductRequest inValue = new TechfixClientDesktopApp.techFixServices.AddNewProductRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.AddNewProductRequestBody();
            inValue.Body.newProduct = newProduct;
            TechfixClientDesktopApp.techFixServices.AddNewProductResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).AddNewProduct(inValue);
            return retVal.Body.AddNewProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewProductResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.AddNewProductAsync(TechfixClientDesktopApp.techFixServices.AddNewProductRequest request) {
            return base.Channel.AddNewProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewProductResponse> AddNewProductAsync(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            TechfixClientDesktopApp.techFixServices.AddNewProductRequest inValue = new TechfixClientDesktopApp.techFixServices.AddNewProductRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.AddNewProductRequestBody();
            inValue.Body.newProduct = newProduct;
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).AddNewProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.GetAllProductsResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.GetAllProducts(TechfixClientDesktopApp.techFixServices.GetAllProductsRequest request) {
            return base.Channel.GetAllProducts(request);
        }
        
        public TechfixClientDesktopApp.techFixServices.Product[] GetAllProducts() {
            TechfixClientDesktopApp.techFixServices.GetAllProductsRequest inValue = new TechfixClientDesktopApp.techFixServices.GetAllProductsRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.GetAllProductsRequestBody();
            TechfixClientDesktopApp.techFixServices.GetAllProductsResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).GetAllProducts(inValue);
            return retVal.Body.GetAllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetAllProductsResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.GetAllProductsAsync(TechfixClientDesktopApp.techFixServices.GetAllProductsRequest request) {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetAllProductsResponse> GetAllProductsAsync() {
            TechfixClientDesktopApp.techFixServices.GetAllProductsRequest inValue = new TechfixClientDesktopApp.techFixServices.GetAllProductsRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.GetAllProductsRequestBody();
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).GetAllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.UpdateProductResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.UpdateProduct(TechfixClientDesktopApp.techFixServices.UpdateProductRequest request) {
            return base.Channel.UpdateProduct(request);
        }
        
        public int UpdateProduct(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            TechfixClientDesktopApp.techFixServices.UpdateProductRequest inValue = new TechfixClientDesktopApp.techFixServices.UpdateProductRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.UpdateProductRequestBody();
            inValue.Body.newProduct = newProduct;
            TechfixClientDesktopApp.techFixServices.UpdateProductResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).UpdateProduct(inValue);
            return retVal.Body.UpdateProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.UpdateProductResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.UpdateProductAsync(TechfixClientDesktopApp.techFixServices.UpdateProductRequest request) {
            return base.Channel.UpdateProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.UpdateProductResponse> UpdateProductAsync(TechfixClientDesktopApp.techFixServices.Product newProduct) {
            TechfixClientDesktopApp.techFixServices.UpdateProductRequest inValue = new TechfixClientDesktopApp.techFixServices.UpdateProductRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.UpdateProductRequestBody();
            inValue.Body.newProduct = newProduct;
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).UpdateProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.AddNewSupplier(TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest request) {
            return base.Channel.AddNewSupplier(request);
        }
        
        public int AddNewSupplier(TechfixClientDesktopApp.techFixServices.Supplier newSupplier) {
            TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest inValue = new TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.AddNewSupplierRequestBody();
            inValue.Body.newSupplier = newSupplier;
            TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).AddNewSupplier(inValue);
            return retVal.Body.AddNewSupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.AddNewSupplierAsync(TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest request) {
            return base.Channel.AddNewSupplierAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.AddNewSupplierResponse> AddNewSupplierAsync(TechfixClientDesktopApp.techFixServices.Supplier newSupplier) {
            TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest inValue = new TechfixClientDesktopApp.techFixServices.AddNewSupplierRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.AddNewSupplierRequestBody();
            inValue.Body.newSupplier = newSupplier;
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).AddNewSupplierAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.GetSuppliersResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.GetSuppliers(TechfixClientDesktopApp.techFixServices.GetSuppliersRequest request) {
            return base.Channel.GetSuppliers(request);
        }
        
        public TechfixClientDesktopApp.techFixServices.Supplier[] GetSuppliers() {
            TechfixClientDesktopApp.techFixServices.GetSuppliersRequest inValue = new TechfixClientDesktopApp.techFixServices.GetSuppliersRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.GetSuppliersRequestBody();
            TechfixClientDesktopApp.techFixServices.GetSuppliersResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).GetSuppliers(inValue);
            return retVal.Body.GetSuppliersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetSuppliersResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.GetSuppliersAsync(TechfixClientDesktopApp.techFixServices.GetSuppliersRequest request) {
            return base.Channel.GetSuppliersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.GetSuppliersResponse> GetSuppliersAsync() {
            TechfixClientDesktopApp.techFixServices.GetSuppliersRequest inValue = new TechfixClientDesktopApp.techFixServices.GetSuppliersRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.GetSuppliersRequestBody();
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).GetSuppliersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.CreateQuotationRequest(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest request) {
            return base.Channel.CreateQuotationRequest(request);
        }
        
        public int CreateQuotationRequest(TechfixClientDesktopApp.techFixServices.Quotation newQuotation, TechfixClientDesktopApp.techFixServices.QuotationDetail[] itemList) {
            TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest inValue = new TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequestBody();
            inValue.Body.newQuotation = newQuotation;
            inValue.Body.itemList = itemList;
            TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse retVal = ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).CreateQuotationRequest(inValue);
            return retVal.Body.CreateQuotationRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse> TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap.CreateQuotationRequestAsync(TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest request) {
            return base.Channel.CreateQuotationRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<TechfixClientDesktopApp.techFixServices.CreateQuotationRequestResponse> CreateQuotationRequestAsync(TechfixClientDesktopApp.techFixServices.Quotation newQuotation, TechfixClientDesktopApp.techFixServices.QuotationDetail[] itemList) {
            TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest inValue = new TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequest();
            inValue.Body = new TechfixClientDesktopApp.techFixServices.CreateQuotationRequestRequestBody();
            inValue.Body.newQuotation = newQuotation;
            inValue.Body.itemList = itemList;
            return ((TechfixClientDesktopApp.techFixServices.TechFixWebServicesSoap)(this)).CreateQuotationRequestAsync(inValue);
        }
    }
}
